### ISSUE TITLE
Is it possible to see more than 7days of information?

### ISSUE THREAD

**Issue by ChrisPark89** [slacknation/medium#7]
I am researching on ETC and ETH to find out how much the hash rate affects the price on both ETC and ETH, but I couldn't find a good source for the hash rate. This one was the best I could find, but it only shows 7 days graph, which is too short for a research. Is there any way I can access those data?

**Comment by slacknation** [comment]
I do not store the history beyond that. But all the data can be easily
retrieved from the blocks.

Sent from my iPhone

On 14 Aug 2016, at 12:17 PM, ChrisPark notifications@github.com wrote:

I am researching on ETC and ETH to find out how much the hash rate affects
the price on both ETC and ETH, but I couldn't find a good source for the
hash rate. This one was the best I could find, but it only shows 7 days
graph, which is too short for a research. Is there any way I can access
those data?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/slacknation/medium/issues/7, or mute the thread

**Comment by ChrisPark89** [comment]
I didn't know that. Thank you for the information.
